// Code generated by 'yaegi extract slices'. DO NOT EDIT.

//go:build go1.26
// +build go1.26

package symbols

import (
	"reflect"
)

func init() {
	Symbols["slices/slices"] = map[string]reflect.Value{}
}
